name: educ_collecteur
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase - On utilise des versions récentes qui fonctionnent bien ensemble
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.7.7

  # PDF & Exportation
  pdf: ^3.10.8
  printing: ^5.11.1
  path_provider: ^2.1.3
  # CORRECTION: On utilise la dernière version stable et publiée
  open_file_plus: ^3.4.1 
  url_launcher: ^6.2.6
  universal_html: ^2.2.4

  # UI & Utils
  provider: ^6.1.2
  intl: ^0.18.1
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  animate_do: ^3.3.4
  fl_chart: ^0.68.0
  image_picker: ^1.1.2
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/applogo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700