// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2T9CsgfkIKiAUqf-QtaiPSql9VHSgwGM',
    appId: '1:55620656912:web:13aff791f8c2b094a34f95',
    messagingSenderId: '55620656912',
    projectId: 'educ-collecteur',
    authDomain: 'educ-collecteur.firebaseapp.com',
    storageBucket: 'educ-collecteur.firebasestorage.app',
    measurementId: 'G-3F8MSZ9P8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7oLlcsd7VR0sMd_KBsU_j_ekFQI1RmmY',
    appId: '1:55620656912:android:695062b7db85b0c5a34f95',
    messagingSenderId: '55620656912',
    projectId: 'educ-collecteur',
    storageBucket: 'educ-collecteur.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf1hjCKPp78-gQiEW__Scx6L3iBO1BEg0',
    appId: '1:55620656912:ios:b4ff5c22dff96e71a34f95',
    messagingSenderId: '55620656912',
    projectId: 'educ-collecteur',
    storageBucket: 'educ-collecteur.firebasestorage.app',
    iosBundleId: 'com.example.educCollecteur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf1hjCKPp78-gQiEW__Scx6L3iBO1BEg0',
    appId: '1:55620656912:ios:b4ff5c22dff96e71a34f95',
    messagingSenderId: '55620656912',
    projectId: 'educ-collecteur',
    storageBucket: 'educ-collecteur.firebasestorage.app',
    iosBundleId: 'com.example.educCollecteur',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2T9CsgfkIKiAUqf-QtaiPSql9VHSgwGM',
    appId: '1:55620656912:web:e7dfe4abe307ea97a34f95',
    messagingSenderId: '55620656912',
    projectId: 'educ-collecteur',
    authDomain: 'educ-collecteur.firebaseapp.com',
    storageBucket: 'educ-collecteur.firebasestorage.app',
    measurementId: 'G-QD8V4M32ZH',
  );
}
